# -*- coding: utf-8 -*-
"""load_to_snowflake.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h9i6_p_yVWfUYe35lJeJSD0cOoGPNlxN
"""

pip install snowflake-connector-python pandas

import pandas as pd
import snowflake.connector
df = pd.read_csv("/content/Sample - Superstore.csv", encoding='latin-1')

df.columns = [col.strip().replace(' ', '_').replace('-', '_').upper()
              for col in df.columns]

print("Columns:", df.columns.tolist())
print("Shape:", df.shape)
print(df.head(2))

import snowflake.connector

conn = snowflake.connector.connect(
    user='XXXXX',
    password='XXX',
    account='XXX',
    warehouse='XXXX',
    database='XXX',
    schema='XX'
)

print("Connected successfully!")

# Commented out IPython magic to ensure Python compatibility.
cursor = conn.cursor()

# ---- INSERT DATA ROW BY ROW ----
insert_query = """
INSERT INTO orders_raw VALUES (
#     %s,%s,%s,%s,%s,%s,%s,%s,%s,%s,
#     %s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s
)
"""

# Convert dataframe to list of tuples
rows = df.astype(str).values.tolist()

# Insert in batches of 500
batch_size = 500
for i in range(0, len(rows), batch_size):
    batch = rows[i:i+batch_size]
    cursor.executemany(insert_query, batch)
    print(f"Inserted rows {i} to {i+len(batch)}")

conn.commit()
print("Done! All rows loaded.")
cursor.close()
conn.close()





